function imprimirMenuPrincipal()

fprintf(['\nBIENVENIDO AL MENU PRINCIPAL DEL CINE\n\n' ...
    '¿Qué le gustaría hacer?\n' ...
    '1. Reservar asiento de una sala.\n' ...
    '2. Visualizar asientos disponibles por sala.\n' ...
    '3. Modificar la reserva de un asiento.\n' ...
    '4. Anular la reserva de un asiento.\n' ...
    '5. Ver la recaudación total del cine.\n' ...
    '6. Salir del programa.\n'])