function imprimirMenuReservar()
% Funcion imprimirMenuReservar:
%       Imprime las opciones del menú de reserva.

fprintf(['\nBIENVENIDO AL MENU DE RESERVA POR SALA DEL CINE\n' ...
    'Primero debe elegir la sala en la que desea reservar.\n' ...
    '¿Qué acción desea realizar?\n\n' ...
    '1. Reservar en SALA 1\n' ...
    '2. Reservar en SALA 2\n' ...
    '3. Reservar en SALA 3\n' ...
    '4. Reservar en SALA 4\n' ...
    '5. Reservar en SALA 5\n' ...
    '6. Volver al menú principal.\n' ...
    '7. Salir del programa.\n\n'])