function imprimirMenuReservar()
% Funcion imprimirMenuReservar:
%       Imprime las opciones del menú de reserva.

fprintf(['<strong>|   MENU RESERVAR   |</strong>\n' ...
    '¿En qué sala le guardaría reservar? Elija el número de la sala:\n' ...
    '1. Reservar en SALA 1\n' ...
    '2. Reservar en SALA 2\n' ...
    '3. Reservar en SALA 3\n' ...
    '4. Reservar en SALA 4\n' ...
    '5. Reservar en SALA 5\n' ...
    '6. Volver al MENÚ PRINCIPAL.\n' ...
    '7. Salir del programa.\n\n'])



